name: Deployment to Github/Gitee pages
on:
  push:
    branches:
      - master
env:
  REACT_APP_DEPLOY_ENV: pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.17.0 ]
    steps:
      - name: Check if this workflow should run
        id: check_workflow
        run: |
          if [[ "${{ vars.WORKFLOW_TO_RUN }}" == "deploy-pages" ]]; then 
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi


      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.check_workflow.outputs.should_run == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        if: steps.check_workflow.outputs.should_run == 'true'
        run: yarn

      - name: Build page
        if: steps.check_workflow.outputs.should_run == 'true'
        run: yarn build

      - name: Deploy to gh-pages
        if: steps.check_workflow.outputs.should_run == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build

      - name: Sync to Gitee
        if: steps.check_workflow.outputs.should_run == 'true'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE }}
        with:
          source-repo: git@github.com:StarForAll/qwerty-learner.git
          destination-repo: git@gitee.com:StarForAll/qwerty-learner.git
