name: Qwerty E2E Workflows
on:
  push:
    branches:
      - master
      - dev/e2e
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this workflow should run
        id: check_workflow
        run: |
          if [[ "${{ vars.WORKFLOW_TO_RUN }}" == "e2e" ]]; then 
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v3
        if: steps.check_workflow.outputs.should_run == 'true'


      - uses: actions/setup-node@v3
        if: steps.check_workflow.outputs.should_run == 'true'
        with:
          node-version: 18

      - name: Cache node modules
        if: steps.check_workflow.outputs.should_run == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.check_workflow.outputs.should_run == 'true'
        run: npm i

      - name: Install Playwright Browsers
        if: steps.check_workflow.outputs.should_run == 'true'
        run: npx playwright install --with-deps

      - name: Run all workflows
        if: steps.check_workflow.outputs.should_run == 'true'
        run: npm run test:e2e || echo "status=failure" >> $GITHUB_ENV
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        if: steps.check_workflow.outputs.should_run == 'true'
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Check workflows status
        if: steps.check_workflow.outputs.should_run == 'true'
        run: if [ "$status" = "failure" ]; then exit 1; fi
